version: "3.2"

volumes:

  data:

services:
  
  bind:
    image: windoac/bind-webmin
    #hostname: "{{.Node.Hostname}}"
    volumes:
      - data:/data
    ports:
      - 10000:10000
      - 53:53
      - 53:53/udp
    environment:
      TZ : Asia/Hong_Kong
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
